name: CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U $${POSTGRES_USER:-postgres}" 
          --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:7
        ports:
          - 6379:6379
    env:
      ConnectionStrings__DefaultConnection: ${{ secrets.POSTGRES_CONNECTION_STRING }}
      Redis: ${{ secrets.REDIS }}
      Jwt__Key: ${{ secrets.JWT_KEY }}
      Jwt__Issuer: ${{ secrets.JWT_ISSUER }}
      Jwt__Audience: ${{ secrets.JWT_AUDIENCE }}
      Jwt__ExpiryMinutes: ${{ secrets.JWT_EXPIRY_MINUTES }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore ./src/OrderManagementSystem/OrderManagementSystem.csproj
      - name: Build
        run: dotnet build --no-restore ./src/OrderManagementSystem/OrderManagementSystem.csproj
      - name: Run all tests
        run: dotnet test --no-build --verbosity normal

  docker:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/nguyen-ordering-system-api:latest ./src/OrderManagementSystem
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/nguyen-ordering-system-api:latest
